default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hola_mundo_development
  username: postgres
  password: 123456
  host: localhost

test:
  <<: *default
  database: hola_mundo_test
  username: postgres
  password: 123456
  host: localhost

production:
  primary: &production_primary
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    <<: *production_primary