default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  host: localhost

development:
  <<: *default
  database: hola_mundo_development

test:
  <<: *default
  database: hola_mundo_test

production:
  <<: *default
  database: hola_mundo_production